### ISSUE TITLE
extract locales - staking

### ISSUE THREAD

**Issue by bf-monster** [betfinio/staking#12]

**Comment by bf-gabagool** [comment]
No Czech translation in:
Lower part (20 results / results per page)
![Image](https://github.com/user-attachments/assets/bf43afa8-83e8-4353-8bd5-08ba25a096f7)

*No results* info in Pooly/Muj Staking/Moje vydelky/Moje vybery
![Image](https://github.com/user-attachments/assets/510163fa-db80-42d2-b229-1ee28cca55e7)

Zacatek cyklu / konec cyklu dates are also in English instead of Czech
![Image](https://github.com/user-attachments/assets/d8d881e4-7a22-4745-af1f-13e43079adbd)
